// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourselec.ocloud.domain.power;

import com.ourselec.ocloud.domain.power.TresourceRolesCompositePK;
import java.io.Serializable;

privileged aspect TresourceRolesCompositePK_Roo_Serializable {
    
    declare parents: TresourceRolesCompositePK implements Serializable;
    
}
