// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourselec.ocloud.domain.power;

import com.ourselec.ocloud.domain.power.Tresources;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Tresources_Roo_Jpa_Entity {
    
    declare @type: Tresources: @Entity;
    
    declare @type: Tresources: @Table(name = "TRESOURCES");
    
}
