// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourselec.ocloud.domain.power;

import com.ourselec.ocloud.domain.power.TresourceRoles;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TresourceRoles_Roo_Configurable {
    
    declare @type: TresourceRoles: @Configurable;
    
}
