// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourselec.ocloud.domain.power;

import com.ourselec.ocloud.domain.power.Troles;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect Troles_Roo_Jpa_Entity {
    
    declare @type: Troles: @Entity;
    
    declare @type: Troles: @Table(name = "TROLES");
    
}
