// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourselec.ocloud.domain;

import com.ourselec.ocloud.domain.DeviceModelRange;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DeviceModelRange_Roo_Configurable {
    
    declare @type: DeviceModelRange: @Configurable;
    
}
