// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ourselec.ocloud.domain;

import com.ourselec.ocloud.domain.DeviceProperty;
import javax.persistence.Entity;

privileged aspect DeviceProperty_Roo_Jpa_Entity {
    
    declare @type: DeviceProperty: @Entity;
    
}
